import {useStoreon} from 'storeon/preact'
import html from './html.js'
import PrivacyPolicyLink from '../component/PrivacyPolicyLink.js'
import StartTime from '../component/summary/StartTime.js'

const messages = {
  hu: {
    "Are you sure you want to cancel this appointment?":
      "Biztosan megszakítja a foglalást?",
    "All inputed data will be lost.": "Minden megadott adat el fog veszni.",
    "No, continue editing appointment": "Nem, időpontfoglalás folytatása",
    "Cancel appointment": "Foglalás megszakítása",
    "Appointment booking failed": "Időpontfoglalás nem sikerült",
    "Due to an unexpected error appointment could not be booked, please restart the process":
      "Az időpontfoglalás közben nem várt hiba történt, kérjük kezdje újra a folyamatot",
    "None of our colleagues is available for the selected process":
      "Egy munkatársunk sem elérhető a választott protokollhoz",
    "First free": "Első szabad",
    "For finding the nearest free time slot.": "A lehető legkorábbi időpont választásához.",
    '@abbrSunday': 'V',
    '@abbrMonday': 'H',
    '@abbrTuesday': 'K',
    '@abbrWednesday': 'Sze',
    '@abbrThursday': 'Cs',
    '@abbrFriday': 'P',
    '@abbrSaturday': 'Szo',
    'January': 'Január',
    'February': 'Február',
    'March': 'Március',
    'April': 'Április',
    'May': 'Május',
    'June': 'Június',
    'July': 'Július',
    'August': 'Augusztus',
    'September': 'Szeptember',
    'October': 'Október',
    'November': 'November',
    'December': 'December',
    'There are no free appointment times for this day': 'Nincsenek szabad időpontok erre a napra',
    "The next free slot is available on %date%": "A következő szabad időpont dátuma: %date%",
    'Go to date': 'Ugrás dátumra',
    'Click here to search for the next free appointment':
      'Kattintson ide a következő szabad időpont kereséséhez',
    'Search in progress...': 'Keresés folyamatban...',
    'Last name': 'Vezetéknév',
    'First name': 'Keresztnév',
    'Birth': 'Születési dátum',
    'Gender': 'Nem',
    'SSN': 'TAJ szám',
    'Country': 'Ország',
    'State': 'Állam',
    'Postal code': 'Irányítószám',
    'City': 'Város',
    'Street address': 'Utca',
    'Mobile': 'Mobil',
    'Select another process': 'Másik protokoll választása',
    '@abbrMinute': 'p.',
    'Not specified': 'Nincs megadva',
    'Male': 'Férfi',
    'Female': 'Nő',
    'Next': 'Tovább',
    'This field is required.': 'Ez a mező kötelező.',
    'Invalid email address.': 'Hibás email cím.',
    'Suspicious input detected: HTML tags are not allowed': 'Gyanús bevitel észlelve: HTML tagek nem engedélyezettek',
    'Your information': 'Az Ön adatai',
    'Name': 'Név',
    'Date of birth': 'Születési dátum',
    'Address': 'Cím',
    'Phone number': 'Telefonszám',
    'Appointment details verification': 'Foglalási adatok ellenőrzése',
    'Appointment summary': 'Foglalási összesítő',
    'Price': 'Ár',
    'Confirm appointment': 'Időpontfoglalás jóváhagyása',
    "%customer%'s examination": '%customer% vizsgálata',
    'Your appointment have been recorded.': 'Foglalását rögzítettük.',
    'The examination will start at %start%, please arrive 5 minutes early.':
      'A vizsgálat kezdete: %start%, kérjük érkezzen 5 perccel korábban.',
    'If you have any further questions, please contact us through our customer service.':
      'Ha kérdése van vagy szeretné módosítani a foglalását, kérjük keresse szaküzletünket.',
    'Appointment booked!': 'Időpont lefoglalva!',
    'examiner: %examiner%': 'végzi: %examiner%',
    'It takes up to %length% minutes': 'Időtartam: %length% perc',
    'I have accepted the privacy policy': html`Elfogadom az <${PrivacyPolicyLink}>adatkezelési tájékoztatóban<//> foglaltakat`,
    'I agree to the use of my medical records according to privacy policy': 'Hozzájárulok egészségügyi adataim adatkezelési tájékoztatóban foglaltak szerinti kezeléséhez',
    'Privacy policy': 'Adatkezelési tájékoztató',
    'Close': 'Bezárás',
    'Start Time': 'Időpont',
    'Subject': 'Tárgy',
    'Location': 'Helyszín',
    'Appointment booking': 'Időpontfoglalás',
    'Select eye examination type': 'Vizsgálattípus választása',
    'Select a vision expert': 'Látásszakértő választása',
    'Select your desired appointment time': 'Időpont választása',
    'Enter customer details': 'Ügyféladatok megadása',
    'Comment': 'Megjegyzés',
    'change date': 'időpont cseréje',
    'More...': 'Bővebben...',
    'Detailed description': 'Részletes leírás',
    'Morning': 'Délelőtt',
    'Afternoon': 'Délután',
    'Evening': 'Este',
    'Booking the appointment': 'Időpont lefoglalása',
    'Event draft': 'Esemény piszkozat',
    'Error! Appointments can not be created! There is a configuration error in the appointment booker that prevents booking. Please contact our store on %mail% email address or book an appointment by calling us and please mention the error then.':
      'Hiba! Időpontfoglalás nem lehetséges! Az időpontfoglaló beállítási hibája miatt nem lehetséges az online időpontfoglalás. Kérjük keresse szaküzletünket a %mail% email címen vagy jelezze nekünk ezt a hibát a telefonos időpontkérés során:',
    'There is a configuration error in the appointment booker that prevents booking. Please call our store to book an appointment us and please mention the error then.':
      'Az időpontfoglaló beállítási hibája miatt nem lehetséges az online időpontfoglalás. Kérjük keresse szaküzletünket és jelezze nekünk ezt a hibát a telefonos időpontkérés során: Nincs email cím beállítva a szaküzlethez.',
    'There is a configuration error in the appointment booker that prevents booking. Please call our store (%tel%) to book an appointment us and please mention the error then: There is no email address configured for this store.':
      'Az időpontfoglaló beállítási hibája miatt nem lehetséges az online időpontfoglalás. Kérjük keresse szaküzletünket a %tel% telefonszámon és jelezze nekünk ezt a hibát a telefonos időpontkérés során: Nincs email cím beállítva a szaküzlethez.',
    'There is no calendar created for this store.': 'Nincs naptár létrehozva az üzlethez.',
    'There is no office hourse configured for this specialist.': 'Nincs munkaóra beállítva a látásszakértőknek.',
    'The eye examination process configured for this appointment booker has been removed.': 'Az időpontfoglalóban beállított vizsgálati protokollt időközben törölték.',
    'There is no email address configured for this store.': 'Nincs email cím beállítva a szaküzlethez.',
    'The lenght isn’t configured for the eye examination processes.': 'A vizsgálati protokollokhoz nincs időtartam megadva.',
    'Invalid API key or inactive API user.': 'Hibás API kulcs vagy inaktív API felhasználó.',
    'Invalid store code': 'Téves üzlet kód',
    'Error! Appointments can not be created!': 'Hiba! Időpontfoglalás nem lehetséges!',
    'There is a configuration error in the appointment booker that prevents booking. Please contact our store on %mail% email address or book an appointment by calling our store (%tel%) and please mention the error then.':
      'Az időpontfoglaló beállítási hibája miatt nem lehetséges az online időpontfoglalás. Kérjük keresse szaküzletünket a %tel% telefonszámon vagy %email% email címen és jelezze nekünk ezt a hibát a telefonos időpontkérés során:',
    'Store selection': 'Üzlet választása',
    'There are no eye examination processes configured in the store network or the length of them is not configured.': 'Nincs vizsgálati protokoll a bolthálózatban, vagy a hossza nincs beállítva.'
  },
  ro: {
    "Are you sure you want to cancel this appointment?":
      "Sunteți sigur că doriți să renunțați la programare?",
    "All inputed data will be lost.": "Datele întroduse se vor pierde.",
    "No, continue editing appointment": "Nu, continuare programare.",
    "Cancel appointment": "Întreruperea programării",
    "Appointment booking failed": "Programare nereușită.",
    "Due to an unexpected error appointment could not be booked, please restart the process":
      "A apărut o eroare. Vă rugăm, începeți din nou procesul.",
    "None of our colleagues is available for the selected process":
      "Nu avem angajați disponibili pentru protocolul selectat.",
    "First free": "Primul liber",
    "For finding the nearest free time slot.": "În cel mai scurt timp.",
    '@abbrSunday': 'D',
    '@abbrMonday': 'L',
    '@abbrTuesday': 'M',
    '@abbrWednesday': 'Mi',
    '@abbrThursday': 'J',
    '@abbrFriday': 'V',
    '@abbrSaturday': 'S',
    'January': 'Ianuarie',
    'February': 'Februarie',
    'March': 'Martie',
    'April': 'Aprilie',
    'May': 'Mai',
    'June': 'Junie',
    'July': 'Julie',
    'August': 'August',
    'September': 'Septembrie',
    'October': 'Octombrie',
    'November': 'Noiembrie',
    'December': 'Decembrie',
    'There are no free appointment times for this day': 'Nu sunt ore libere la data selectată.',
    "The next free slot is available on %date%": "Următorul timp liber este: %date%",
    'Go to date': 'Salt la dată',
    'Click here to search for the next free appointment':
      'Click aici pentru căutarea următorului timp liber',
    'Search in progress...': 'Căutare în curs...',
    'Last name': 'Nume',
    'First name': 'Prenume',
    'Birth': 'Data naștere',
    'Gender': 'Gen',
    'SSN': 'CNP',
    'Country': 'Țara',
    'State': 'Megye',
    'Postal code': 'Cod poștal',
    'City': 'Oraș',
    'Street address': 'Strada',
    'Mobile': 'Număr de tel mobil',
    'Select another process': 'Selectare protocol diferit',
    '@abbrMinute': 'min.',
    'Not specified': 'Nu e specificat',
    'Male': 'Bărbat',
    'Female': 'Femeie',
    'Next': 'Mai departe',
    'This field is required.': 'Acest cămp este necesar.',
    'Invalid email address.': 'Adresa da mail greșită.',
    'Your information': 'Datele personale',
    'Name': 'Nume',
    'Date of birth': 'Data naștere',
    'Address': 'Adresa',
    'Phone number': 'Număr de telefon',
    'Appointment details verification': 'Verifică datele rezervării',
    'Appointment summary': 'Sumar rezervare',
    'Price': 'Preț',
    'Confirm appointment': 'Rezervare',
    "%customer%'s examination": 'Consultație %customer%',
    'Your appointment have been recorded.': 'Consultația a fost programată',
    'The examination will start at %start%, please arrive 5 minutes early.':
      'Vă rugăm să vă prezentați cu 5 minute mai devreme față de ora %start%.',
    'If you have any further questions, please contact us through our customer service.':
      'Dacă aveți alte întrebări, vă rugăm să ne contactați.',
    'Appointment booked!': 'Programare rezervată!',
    'examiner: %examiner%': 'examinator: %examiner%',
    'It takes up to %length% minutes': 'Durata: %length% minute',
    'I have accepted the privacy policy': html`Accept <${PrivacyPolicyLink}>Termenii și condițiile<//>`,
    'I agree to the use of my medical records according to privacy policy': 'Sunt de acord cu prelucrarea datelor medicale conform Termenilor și condițiilor generale.',
    'Privacy policy': 'Termeni și condiții',
    'Close': 'Închidere',
    'Start Time': 'Data',
    'Subject': 'Subiect',
    'Location': 'Locație',
    'Appointment booking': 'Programare',
    'Select eye examination type': 'Selectează tipul de examinare dorit',
    'Select a vision expert': 'Alege specialistul în sănătatea ochilor',
    'Select your desired appointment time': 'Selectare dată și oră',
    'Enter customer details': 'Datele clientului',
    'change date': 'modificare dată',
    'Morning': 'Înainte de masă',
    'Afternoon': 'După masă',
    'Evening': 'Seara',
    'Booking the appointment': 'Rezervarea unei programări',
    'Event draft': 'Eveniment schiță',
    'Error! Appointments can not be created! There is a configuration error in the appointment booker that prevents booking. Please contact our store on %mail% email address or book an appointment by calling us and please mention the error then.':
      'Eroare! Programarea nu se poate rezerva! Rezervarea online a programărilor nu este posibilă din cauza unei erori de configurare în sistemul de rezervare a programărilor. Vă rugăm să contactați magazinul la adresa de e-mail %mail% și să ne informați despre această eroare în timpul solicitării de programare telefonică',
    'There is a configuration error in the appointment booker that prevents booking. Please call our store to book an appointment us and please mention the error then.':
      'Rezervarea online nu este posibilă din cauza unei erori de configurare în calendarul de rezervare. Vă rugăm contactați magazinul, informați-ne despre această eroare în timpul solicitării de programare telefonică: Nu a fost setată nicio adresă de e-mail pentru magazinul de specialitate.',
    'There is a configuration error in the appointment booker that prevents booking. Please call our store (%tel%) to book an appointment us and please mention the error then: There is no email address configured for this store.':
      'Rezervarea online nu este posibilă din cauza unei erori de configurare în calendarul de rezervare. Vă rugăm contactați magazinul telefonic ( %tel% ), informați-ne despre această eroare în timpul solicitării de programare telefonică: Nu a fost setată nicio adresă de e-mail pentru magazinul de specialitate.',
    'There is no calendar created for this store.': 'Nu a fost creat calendar pentru acest magazin.',
    'There is no office hourse configured for this specialist.': 'Nu există ore de lucru pentru specialiștii în vedere.',
    'The eye examination process configured for this appointment booker has been removed.': 'Protocolul de examinare stabilit la programare a fost anulat între timp.',
    'There is no email address configured for this store.': 'Nu există nicio adresă de e-mail setată pentru magazinul specializat.',
    'The lenght isn’t configured for the eye examination processes.': 'Nu este specificată durată pentru protocoalele de examinare.',
    'Invalid API key or inactive API user.': 'Cheie API greșită sau utilizator API inactiv.',
    'Invalid store code': 'Cod magazin greșit',
    'Error! Appointments can not be created!': 'Eroare! Programarea nu se poate rezerva!',
    'There is a configuration error in the appointment booker that prevents booking. Please contact our store on %mail% email address or book an appointment by calling our store (%tel%) and please mention the error then.':
      'Eroare! Programarea nu se poate rezerva! Rezervarea online a programărilor nu este posibilă din cauza unei erori de configurare în sistemul de rezervare a programărilor. Vă rugăm să contactați magazinul la numărul de telefon %tel% sau adresa de e-mail %email% și să ne raportați această eroare atunci când solicitați o programare prin telefon:',
    'Store selection': 'Selectare magazin',
    'There are no eye examination processes configured in the store network or the length of them is not configured.': 'Nu există protocol de consulație în magazin sau durata protocolului nu este specificat.',
    'Suspicious input detected: HTML tags are not allowed': 'Intrare suspectă detectată: etichetele HTML nu sunt permise'
  },
  hr: {
    "Are you sure you want to cancel this appointment?": "Jeste li sigurni da želite otkazati ovaj termin?",
    "All inputed data will be lost.": "Svi uneseni podaci bit će izgubljeni.",
    "No, continue editing appointment": "Ne, nastavi s uređivanjem termina",
    "Cancel appointment": "Otkaži termin",
    "Appointment booking failed": "Rezervacija termina nije uspjela",
    "Due to an unexpected error appointment could not be booked, please restart the process":
      "Zbog neočekivane pogreške termin nije moguće rezervirati, molimo ponovno pokrenite proces",
    "None of our colleagues is available for the selected process":
      "Nitko od naših kolega nije dostupan za odabrani proces",
    "First free": "Prvo slobodno",
    "For finding the nearest free time slot.": "Da odaberete što raniji termin.",
    '@abbrSunday': 'N',
    '@abbrMonday': 'P',
    '@abbrTuesday': 'U',
    '@abbrWednesday': 'S',
    '@abbrThursday': 'Č',
    '@abbrFriday': 'P',
    '@abbrSaturday': 'S',
    'January': 'Siječnja',
    'February': 'Veljača',
    'March': 'Ožujak',
    'April': 'Travanj',
    'May': 'Svibanj',
    'June': 'Lipanj',
    'July': 'Srpanj',
    'August': 'Kolovoz',
    'September': 'Rujan',
    'October': 'Listopad',
    'November': 'Studeni',
    'December': 'Prosinac',
    'There are no free appointment times for this day': 'Za ovaj dan nema slobodnih termina',
    "The next free slot is available on %date%": "Datum sljedećeg slobodnog termina je %date%",
    'Go to date': 'Skoči na datum',
    'Click here to search for the next free appointment': 'Traženje sljedećeg slobodnog termina',
    'Search in progress...': 'Pretraživanje je u tijeku...',
    'Last name': 'Prezime',
    'First name': 'Ime',
    'Birth': 'Datum rođenja',
    'Gender': 'Spol',
    'SSN': 'MBO broj',
    'Country': 'Zemlja',
    'State': 'Država',
    'Postal code': 'Poštanski broj',
    'City': 'Grad',
    'Street address': 'Ulica',
    'Mobile': 'Mobilni',
    'Select another process': 'Odaberite drugi protokol',
    '@abbrMinute': 'm.',
    'Not specified': 'Nije specificirano',
    'Male': 'Muškarac',
    'Female': 'Žena',
    'Next': 'Sljedeći',
    'This field is required.': 'Ovo polje je obavezno.',
    'Invalid email address.': 'Pogrešna adresa e-maila.',
    'Your information': 'Vaši podaci',
    'Name': 'Ime',
    'Date of birth': 'Datum rođenja',
    'Address': 'Adresa',
    'Phone number': 'Broj telefona',
    'Appointment details verification': 'Provjerite detalje rezervacije',
    'Appointment summary': 'Sažetak rezervacije',
    'Price': 'Cjena',
    'Confirm appointment': 'Odobrenje rezervacije termina',
    "%customer%'s examination": '%customer% pregleda',
    'Your appointment have been recorded.': 'Vaša rezervacija je zabilježena.',
    'The examination will start at %start%, please arrive 5 minutes early.':
      'Početak pregleda: %start%, molimo dođite 5 minuta ranije.',
    'If you have any further questions, please contact us through our customer service.':
      'Ako imate dodatnih pitanja, obratite nam se putem naše korisničke službe.',
    'Appointment booked!': 'Termin rezerviran!',
    'examiner: %examiner%': 'ispitivač: %examiner%',
    'It takes up to %length% minutes': 'Trajanje: %length% minuta',
    'I have accepted the privacy policy': html`Prihvaćam <${PrivacyPolicyLink}>što je zapisano<//> u informativnom listu za upravljanje podacima`,
    'I agree to the use of my medical records according to privacy policy': 'Pristajem na obradu mojih zdravstvenih podataka u skladu s informacijama o upravljanju podacima',
    'Privacy policy': 'Informativni list za upravljanje podatke',
    'Close': 'Zatvaranje',
    'Start Time': 'Vrijeme početka',
    'Subject': 'Objekat',
    'Location': 'Mjesto',
    'Appointment booking': 'Zakažite termin',
    'Select eye examination type': 'Izbor vrste pregleda',
    'Select a vision expert': 'Odaberite stručnjaka za vid',
    'Select your desired appointment time': 'Odaberite željeno vrijeme termina',
    'Enter customer details': 'Unos podataka o klijentu',
    'change date': 'promijeni termin',
    'Morning': 'Prijepodne',
    'Afternoon': 'Poslijepodne',
    'Evening': 'Večer',
    'Booking the appointment': 'Rezerviranje termina',
    'Event draft': 'Skica za događaj',
    'Error! Appointments can not be created! There is a configuration error in the appointment booker that prevents booking. Please contact our store on %mail% email address or book an appointment by calling us and please mention the error then.':
      'Greška! Rezervacija termina nije moguća! Online rezervacija termina nije moguća zbog greške u konfiguraciji sustava za rezervaciju termina. Kontaktirajte našu optiku na e-mail adresu %mail% i prijavite nam ovu pogrešku tijekom telefonskog zahtjeva za termin.',
    'There is a configuration error in the appointment booker that prevents booking. Please call our store to book an appointment us and please mention the error then.':
      'Online rezervacija termina nije moguća zbog greške u konfiguraciji sustava za rezervaciju termina. Kontaktirajte našu optiku i prijavite nam ovu pogrešku tijekom telefonskog zahtjeva za termin. Nije postavljena e-mail adresa za optiku.',
    'There is a configuration error in the appointment booker that prevents booking. Please call our store (%tel%) to book an appointment us and please mention the error then: There is no email address configured for this store.':
      'Online rezervacija termina nije moguća zbog greške u konfiguraciji sustava za rezervaciju termina. Nazovite našu optiku na telefonski broj %tel% i prijavite nam ovu pogrešku tijekom telefonskog zahtjeva za termin. Nije postavljena e-mail adresa za optiku.',
    'There is no calendar created for this store.': 'Kalendar nije napravljen za optiku.',
    'There is no office hourse configured for this specialist.': 'Za specijaliste za vid nije određeno radno vrijeme.',
    'The eye examination process configured for this appointment booker has been removed.': 'Zadan protokol pregleda kod rezervacija termina je u međuvremenu izbrisan.',
    'There is no email address configured for this store.': 'Nije postavljena e-mail adresa za optiku.',
    'The lenght isn’t configured for the eye examination processes.': 'Kod protokola pregleda nije navedeno trajanje.',
    'Invalid API key or inactive API user.': 'Loš API ključ ili neaktivan API korisnik.',
    'Invalid store code': 'Pogrešan kod optike',
    'Error! Appointments can not be created!': 'Greška! Rezervacija termina nije moguća!',
    'There is a configuration error in the appointment booker that prevents booking. Please contact our store on %mail% email address or book an appointment by calling our store (%tel%) and please mention the error then.':
      'Online rezervacija termina nije moguća zbog greške u konfiguraciji sustava za rezervaciju termina. Kontaktirajte našu optiku na %tel% telefonski broj ili na %email% email adresu i  prijavite nam ovu pogrešku tijekom telefonskog zahtjeva za termin. ',
    'Store selection': 'Odabir trgovine',
    'There are no eye examination processes configured in the store network or the length of them is not configured.': 'U optici nije postavljen protokol pregleda ili nije određeno duljina pregleda.',
    'Suspicious input detected: HTML tags are not allowed': 'Sumnjiv unos otkriven: HTML oznake nisu dopuštene'
  },
  en: {
    '@abbrSunday': 'Sun',
    '@abbrMonday': 'Mon',
    '@abbrTuesday': 'Tue',
    '@abbrWednesday': 'Wed',
    '@abbrThursday': 'Thu',
    '@abbrFriday': 'Fri',
    '@abbrSaturday': 'Sat',
    'January': 'January',
    'February': 'February',
    'March': 'March',
    'April': 'April',
    'May': 'May',
    'June': 'June',
    'July': 'July',
    'August': 'August',
    'September': 'September',
    'October': 'October',
    'November': 'November',
    'December': 'December',
    '@abbrMinute': 'm.',
    'I have accepted the privacy policy': html`I accept the terms of <${PrivacyPolicyLink}>privacy policy<//>`,
    'Your appointment starts at startTime': html`Your appointment starts at <${StartTime}//>`,
    'change date': 'change date'
  }
};

export default (message, params = {}, storeContent) => {
  storeContent = storeContent || useStoreon('language', 'translationOverrides');
  let language = storeContent.language;

  const languageSpecificMessages = messages[language] || messages[language.substring(0, 2)] || messages.en;
  message = storeContent.translationOverrides[message] || languageSpecificMessages[message] || message;

  for (const key in params) {
    message = message.replace(new RegExp('%' + key + '%', 'g'), params[key]);
  }

  return message;
}
